### ISSUE TITLE
難易度変更部の冗長

### ISSUE THREAD

**Issue by yu-kod** [c0a21123/ProjExD#28]
https://github.com/c0a21123/ProjExD/blob/3daa0708aa7e3b3fd69be743edd8d49b40e1a97a/ex05/fight_kokaton.py#L97
似たようなコードが繰り返されていて冗長です．
関数化するか，速度情報を配列にして繰り返しで処理できるようにしてください．

**Comment by c0a21085** [comment]
コメントありがとうございます！
修正しました。

**Comment by c0a21123** [comment]
close
