### ISSUE TITLE
まとめれそう

### ISSUE THREAD

**Issue by c0a21085** [c0a21123/ProjExD#3]
https://github.com/c0a21123/ProjExD/blob/a75c1f0c46830574e1cb6dbd86e689e7eada3123/ex02/calc.py#L9
siki = entry.get() # 数式の文字列
res = eval(siki) # 数式文字列の評価 
を、res = eval(entry.get())で一文でまとめられそう！

**Comment by c0a21123** [comment]
具体的に教えてくれてありがとう

**Comment by c0a21123** [comment]
close issue
