### ISSUE TITLE
あ

### ISSUE THREAD

**Issue by c0a21085** [c0a21123/ProjExD#5]
https://github.com/c0a21123/ProjExD/blob/485c46510cd7f5f9a92751beba1363ab1e18db23/ex03/maze.py#L18
それぞれのif文にdeleteを入れなくても良さそう？
if文外でひとまとめにできそうな気がした。

**Comment by c0a21123** [comment]
if key:
        canvas.delete(f"{tag_inf}") #タグ指定し、移動前のこうかとんを削除

に変更しました、ありがとう、

**Comment by c0a21123** [comment]
issueを閉じる
